SKILL_NAME = "c4-codebase"
SKILL_FILE_NAME = "SKILL.md"
MIN_PYTHON_VERSION = (3, 7)

STATE_SCHEMA_VERSION = 2
LEGACY_STATE_SCHEMA_VERSION = 1
SCAN_FORMAT_VERSION = 2

WORKSPACE_DIR_NAME = ".c4-codebase"
EXTERNAL_WORKSPACE_HOME_ENV = "C4_CODEBASE_HOME"
EXTERNAL_WORKSPACE_HOME_DEFAULT = "~/.c4-codebase"
DEFAULT_OUTPUT_DIR = "docs/architecture"
ROOT_COMMIT_ID_LENGTH = 12

WORKSPACE_SOURCE_ARGUMENT = "argument"
WORKSPACE_SOURCE_REPOSITORY = "repository"
WORKSPACE_SOURCE_EXTERNAL = "external"
WORKSPACE_SOURCE_DEFAULT = "repository-default"

VERSIONING_SHARED = "shared"
VERSIONING_LOCAL = "local"
VERSIONING_POLICIES = (VERSIONING_SHARED, VERSIONING_LOCAL)
WORKSPACE_GITIGNORE_NAME = ".gitignore"
WORKSPACE_GITIGNORE_CONTENT = {
    VERSIONING_SHARED: "scan.json\nscan.md\nbackups/\n",
    VERSIONING_LOCAL: "*\n",
}

GIT_TIMEOUT_SECONDS = 30
HASH_CHUNK_BYTES = 65536
FINGERPRINT_HEX_LENGTH = 16
JSON_INDENT = 2
RECORD_ID_DIGITS = 3
DIRTY_PATHS_LIMIT = 50
INVALIDATION_PATHS_LIMIT = 100
PUBLISH_OTHER_FILES_LIMIT = 100
BATCH_ERRORS_LIMIT = 20
TIMESTAMP_FOR_PATH_FORMAT = "%Y%m%dT%H%M%SZ"
DEFAULT_FILE_MODE = 0o666

STATUS_PATH_COLUMN_WIDTH = 42
STATUS_EXISTS_COLUMN_WIDTH = 7
STATUS_MODIFIED_COLUMN_WIDTH = 25
STATUS_SIZE_COLUMN_WIDTH = 10

ARTIFACT_MARKER_PREFIX = "c4-codebase:"
GENERATED_MARKER = "c4-codebase:generated"
TEMPLATE_MARKER = "c4-codebase:template"
MARKER_KIND_GENERATED = "generated"
MARKER_KIND_TEMPLATE = "template"
MARKER_SCAN_LINES = 5

EXIT_OK = 0
EXIT_INTERNAL_ERROR = 1
EXIT_USAGE = 2
EXIT_UNHEALTHY = 3
EXIT_PUBLICATION_BLOCKED = 4
EXIT_OPERATIONAL_ERROR = 5

SCAN_MAX_FILES_DEFAULT = 200000
SCAN_LIST_LIMIT = 200
SCAN_TOP_DENSITY_LIMIT = 30
SCAN_RECENT_COMMITS = 20
SCAN_CHURN_COMMITS = 100
SCAN_CHURN_PATHS_LIMIT = 25
SCAN_TREE_DEPTH = 2
SCAN_TREE_LIMIT = 150
SCAN_EXCLUDED_COUNT_LIMIT = 10000
SCAN_WALK_ERRORS_LIMIT = 50
SCAN_DEFINITION_MAX_BYTES = 1048576
