from __future__ import annotations

from pathlib import Path
from typing import List

from .fsutil import write_text_atomic
from .layout import QUESTIONS_MARKDOWN_FILE
from .ledger import effective_records
from .vocabulary import QUESTION_ANSWERED, QUESTION_DISMISSED, QUESTION_OPEN

HEADER = (
    "# C4 Codebase Questions\n\n"
    "Rendered from `questions.jsonl` by `workspace.py question render`. Do not edit this file by hand.\n"
)
SECTIONS = ((QUESTION_OPEN, "Open"), (QUESTION_ANSWERED, "Answered"), (QUESTION_DISMISSED, "Dismissed"))
EMPTY_SECTION = "- None\n"


def render_questions(records: List[dict]) -> str:
    view = effective_records(records)
    parts = [HEADER]
    for status, title in SECTIONS:
        items = [_render_item(record) for record in view if record["status"] == status]
        parts.append(f"## {title}\n\n" + ("".join(items) if items else EMPTY_SECTION))
    return "\n".join(parts)


def _render_item(record: dict) -> str:
    context = [f"impact: {record['impact']}"]
    if record.get("unit"):
        context.append(f"unit: {record['unit']}")
    if record.get("hypothesisIds"):
        context.append("hypotheses: " + ", ".join(record["hypothesisIds"]))
    text = f"- **{record['id']}** ({'; '.join(context)}) {record['question']}\n"
    if record["status"] == QUESTION_ANSWERED:
        text += f"  - Answer: {record['answer']} (evidence {record['answerEvidence']})\n"
    if record["status"] == QUESTION_DISMISSED:
        text += f"  - Dismissed: {record['dismissalReason']}\n"
    return text


def write_questions_markdown(workspace: Path, records: List[dict]) -> None:
    write_text_atomic(workspace / QUESTIONS_MARKDOWN_FILE, render_questions(records))


def questions_markdown_in_sync(workspace: Path, records: List[dict]) -> bool:
    path = workspace / QUESTIONS_MARKDOWN_FILE
    return path.exists() and path.read_text(encoding="utf-8") == render_questions(records)
