from __future__ import annotations

import argparse
import html
import re
from pathlib import Path
from typing import Dict, List, Optional, Sequence

from .cli_support import build_parser, emit_json, run_cli
from .constants import EXIT_OK, EXIT_OPERATIONAL_ERROR, EXIT_PUBLICATION_BLOCKED, EXIT_USAGE, MARKER_KIND_GENERATED
from .errors import DiscoveryError
from .fsutil import read_json, read_text, utc_now, write_text_atomic
from .layout import TEMPLATES_DIR
from .markdown_html import markdown_to_html
from .markers import artifact_marker_kind, generated_header
from .schema import load_schema, validate
from .skillmeta import skill_root

PROG = "render-report.py"
REPORT_SCHEMA = "report"
REPORT_TEMPLATE = "report.html"
REPORT_FILE_NAME = "index.html"
SVG_SUFFIX = ".svg"
LEGEND_SUFFIX = "-key"
DEFAULT_LANG = "en"
DOCUMENT_KEY_PREFIX = "doc-"
DOCUMENT_HEADING_OFFSET = 1
MARKDOWN_SUFFIX = ".md"
FIRST_HEADING = re.compile(r"\A<h2>.*?</h2>\n?", re.DOTALL)
UNKNOWN_VALUE = "unknown"
TEMPLATE_MARKER_LINE = "<!-- c4-codebase:template -->"
PLACEHOLDER = re.compile(r"\{\{([a-z_]+)\}\}")
BLOCK = re.compile(r'<template id="([a-z-]+)">\n?(.*?)</template>\n?', re.DOTALL)
SVG_PROLOG = re.compile(r"\A\s*(?:<\?xml[^>]*\?>\s*)?(?:<!DOCTYPE[^>]*>\s*)?", re.IGNORECASE)
KEY_CLEANER = re.compile(r"[^a-zA-Z0-9]+")
PARAGRAPH_SPLIT = re.compile(r"\n\s*\n")
DEFAULT_LABELS = {
    "kicker": "Architecture diagrams",
    "intro": "About these diagrams",
    "skip": "Skip to content",
    "repository": "Repository",
    "revision": "Revision",
    "generated": "Generated",
    "diagrams": "Diagrams",
    "documents": "Documents",
    "fit": "Fit width",
    "actual": "Actual size",
    "fullscreen": "Full screen",
    "download": "Download SVG",
    "legend": "Legend",
    "footer": "Generated by the c4-codebase skill from the repository's Structurizr DSL model. Diagrams are derived outputs; the Markdown documents and workspace.dsl are the source of truth.",
}
MANIFEST_HINT = "see schemas/report.schema.json: title, diagrams[{file, title, description}], optional lang, repository, revision, intro, documents, labels"


def main(argv: Optional[Sequence[str]] = None, description: str = "") -> int:
    args = build_report_parser(description).parse_args(argv)
    return run_cli(lambda: execute(args), args.json)


def build_report_parser(description: str) -> argparse.ArgumentParser:
    parser = build_parser(PROG, description)
    parser.add_argument("--diagrams", required=True, help="directory with the rendered .svg files (export-diagrams.sh --svg output)")
    parser.add_argument("--manifest", required=True, help="JSON manifest with title, intro, and one entry per diagram (schemas/report.schema.json)")
    parser.add_argument("--output", help=f"HTML file to write (default: <diagrams>/{REPORT_FILE_NAME})")
    parser.add_argument("--json", action="store_true", help="print a JSON summary instead of text")
    return parser


def execute(args: argparse.Namespace) -> int:
    diagrams_dir = Path(args.diagrams)
    if not diagrams_dir.is_dir():
        raise DiscoveryError(f"diagrams directory not found: {diagrams_dir}", EXIT_OPERATIONAL_ERROR, hint="run export-diagrams.sh --svg first")
    manifest = load_manifest(Path(args.manifest))
    output = Path(args.output) if args.output else diagrams_dir / REPORT_FILE_NAME
    require_writable_target(output)
    page = render(manifest, diagrams_dir, load_template())
    write_text_atomic(output, page)
    summary = {
        "written": str(output),
        "diagrams": len(manifest["diagrams"]),
        "legends": sum(1 for item in manifest["diagrams"] if legend_path(diagrams_dir, item["file"]) is not None),
        "documents": len(manifest.get("documents", [])),
    }
    if args.json:
        emit_json(summary)
    else:
        print(f"Wrote {output} ({summary['diagrams']} diagrams, {summary['legends']} legends, {summary['documents']} document links)")
    return EXIT_OK


def load_manifest(path: Path) -> dict:
    if not path.is_file():
        raise DiscoveryError(f"manifest not found: {path}", EXIT_USAGE, hint=MANIFEST_HINT)
    manifest = read_json(path)
    problems = validate(manifest, load_schema(REPORT_SCHEMA))
    if problems:
        raise DiscoveryError("invalid manifest: " + "; ".join(problems), EXIT_USAGE, hint=MANIFEST_HINT)
    files = [item["file"] for item in manifest["diagrams"]]
    duplicates = sorted({name for name in files if files.count(name) > 1})
    if duplicates:
        raise DiscoveryError("invalid manifest: duplicate diagram files: " + ", ".join(duplicates), EXIT_USAGE, hint=MANIFEST_HINT)
    return manifest


def load_template() -> str:
    path = skill_root() / TEMPLATES_DIR / REPORT_TEMPLATE
    if not path.is_file():
        raise DiscoveryError(f"report template not found: {path}", EXIT_OPERATIONAL_ERROR, hint="the skill installation is incomplete")
    text = read_text(path)
    if TEMPLATE_MARKER_LINE not in text:
        raise DiscoveryError(f"report template lacks the template marker: {path}", EXIT_OPERATIONAL_ERROR)
    return text


def require_writable_target(output: Path) -> None:
    if output.exists() and artifact_marker_kind(output) != MARKER_KIND_GENERATED:
        raise DiscoveryError(
            f"refusing to overwrite a file the skill did not generate: {output}",
            EXIT_PUBLICATION_BLOCKED,
            hint="pass --output with another path, or ask the user before replacing it",
        )


def render(manifest: dict, diagrams_dir: Path, template: str) -> str:
    blocks, shell = split_blocks(template)
    labels = dict(DEFAULT_LABELS, **manifest.get("labels", {}))
    svgs = collect_svgs(diagrams_dir, manifest["diagrams"])
    values = {
        "lang": html.escape(manifest.get("lang", DEFAULT_LANG), quote=True),
        "title": html.escape(manifest["title"]),
        "repository": html.escape(manifest.get("repository") or UNKNOWN_VALUE),
        "revision": html.escape(manifest.get("revision") or UNKNOWN_VALUE),
        "generated_at": utc_now(),
        "intro": paragraphs(manifest.get("intro", "")),
        "nav": "".join(fill(blocks["nav-item"], nav_values(index, item)) for index, item in enumerate(manifest["diagrams"], start=1)),
        "documents": documents_block(blocks, manifest.get("documents", []), labels),
        "sections": "".join(
            fill(blocks["diagram-section"], section_values(blocks, index, item, svgs, diagrams_dir, labels))
            for index, item in enumerate(manifest["diagrams"], start=1)
        ),
        "document_sections": document_sections(blocks, manifest.get("documents", []), diagrams_dir, labels),
    }
    values.update({f"label_{name}": html.escape(text) for name, text in labels.items()})
    page = fill(shell, values)
    page = page.replace(TEMPLATE_MARKER_LINE, generated_header(Path(REPORT_FILE_NAME), manifest.get("revision"), values["generated_at"]).rstrip("\n"), 1)
    leftover = sorted(set(PLACEHOLDER.findall(page)))
    if leftover:
        raise DiscoveryError("template placeholders without a value: " + ", ".join(leftover), EXIT_OPERATIONAL_ERROR)
    return page


def split_blocks(template: str):
    blocks: Dict[str, str] = {name: body for name, body in BLOCK.findall(template)}
    for required in ("nav-item", "documents-block", "document-item", "diagram-section", "legend-block", "documents-main", "document-section"):
        if required not in blocks:
            raise DiscoveryError(f"report template lacks the <template id=\"{required}\"> block", EXIT_OPERATIONAL_ERROR)
    return blocks, BLOCK.sub("", template)


def fill(block: str, values: Dict[str, str]) -> str:
    def substitute(match) -> str:
        name = match.group(1)
        return values[name] if name in values else match.group(0)
    return PLACEHOLDER.sub(substitute, block)


def collect_svgs(diagrams_dir: Path, diagrams: List[dict]) -> Dict[str, str]:
    listed = {item["file"] for item in diagrams}
    present = {path.name for path in diagrams_dir.glob(f"*{SVG_SUFFIX}")}
    missing = sorted(listed - present)
    if missing:
        raise DiscoveryError("manifest lists diagrams that are not in the directory: " + ", ".join(missing), EXIT_USAGE, hint="render them with export-diagrams.sh --svg or fix the file names")
    unlisted = sorted(name for name in present - listed if not is_legend(name))
    if unlisted:
        raise DiscoveryError("diagrams without a manifest entry: " + ", ".join(unlisted), EXIT_USAGE, hint="describe every diagram in the manifest; only *-key.svg legends are attached automatically")
    return {name: read_svg(diagrams_dir / name) for name in listed}


def is_legend(name: str) -> bool:
    return name.endswith(f"{LEGEND_SUFFIX}{SVG_SUFFIX}")


def legend_path(diagrams_dir: Path, diagram_file: str) -> Optional[Path]:
    candidate = diagrams_dir / f"{diagram_file[:-len(SVG_SUFFIX)]}{LEGEND_SUFFIX}{SVG_SUFFIX}"
    return candidate if candidate.is_file() else None


def read_svg(path: Path) -> str:
    body = SVG_PROLOG.sub("", read_text(path), count=1).strip()
    if not body.startswith("<svg"):
        raise DiscoveryError(f"not an SVG document: {path}", EXIT_USAGE, hint="export-diagrams.sh --svg writes one .svg per view")
    return body


def nav_values(index: int, item: dict) -> Dict[str, str]:
    return {"key": section_key(item["file"]), "number": str(index), "diagram_title": html.escape(item["title"])}


def section_values(blocks: Dict[str, str], index: int, item: dict, svgs: Dict[str, str], diagrams_dir: Path, labels: Dict[str, str]) -> Dict[str, str]:
    legend = legend_path(diagrams_dir, item["file"])
    values = {
        "key": section_key(item["file"]),
        "number": str(index),
        "diagram_title": html.escape(item["title"]),
        "description": paragraphs(item["description"]),
        "file": html.escape(item["file"]),
        "svg": svgs[item["file"]],
        "legend": fill(blocks["legend-block"], {"legend_svg": read_svg(legend), "label_legend": html.escape(labels["legend"])}) if legend else "",
    }
    values.update({f"label_{name}": html.escape(text) for name, text in labels.items()})
    return values


def documents_block(blocks: Dict[str, str], documents: List[dict], labels: Dict[str, str]) -> str:
    if not documents:
        return ""
    items = "".join(fill(blocks["document-item"], {"href": f"#{document_key(doc['file'])}", "document_title": html.escape(doc["title"])}) for doc in documents)
    return fill(blocks["documents-block"], {"items": items, "label_documents": html.escape(labels["documents"])})


def document_sections(blocks: Dict[str, str], documents: List[dict], diagrams_dir: Path, labels: Dict[str, str]) -> str:
    if not documents:
        return ""
    items = "".join(
        fill(blocks["document-section"], {
            "key": document_key(doc["file"]),
            "document_title": html.escape(doc["title"]),
            "file": html.escape(doc["file"]),
            "body": document_body(diagrams_dir, doc["file"]),
        })
        for doc in documents
    )
    return fill(blocks["documents-main"], {"items": items, "label_documents": html.escape(labels["documents"])})


def document_body(diagrams_dir: Path, relative: str) -> str:
    path = (diagrams_dir / relative).resolve()
    if not path.is_file():
        raise DiscoveryError(f"document not found: {relative} (resolved from {diagrams_dir})", EXIT_USAGE, hint="documents[].file is relative to the diagrams directory; publish the documents first")
    text = read_text(path)
    if path.suffix.lower() == MARKDOWN_SUFFIX:
        return FIRST_HEADING.sub("", markdown_to_html(text, DOCUMENT_HEADING_OFFSET), count=1)
    return f"<pre><code>{html.escape(text, quote=False)}</code></pre>\n"


def document_key(relative: str) -> str:
    stem = Path(relative).name
    return DOCUMENT_KEY_PREFIX + KEY_CLEANER.sub("-", stem).strip("-").lower()


def section_key(file_name: str) -> str:
    stem = file_name[:-len(SVG_SUFFIX)]
    return "d-" + KEY_CLEANER.sub("-", stem).strip("-").lower()


def paragraphs(text: str) -> str:
    chunks = [chunk.strip() for chunk in PARAGRAPH_SPLIT.split(text.strip()) if chunk.strip()]
    return "".join(f"<p>{html.escape(chunk)}</p>\n" for chunk in chunks)
